# Generated by Django 5.2.8 on 2025-12-02 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("token", models.TextField(blank=True, null=True)),
                ("refreshToken", models.TextField(blank=True, null=True)),
                ("socialId", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profileType",
                    models.CharField(default="User", max_length=255, null=True),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.BigIntegerField(default=1764657972053)),
                ("updatedAt", models.BigIntegerField()),
                ("deletedAt", models.BigIntegerField()),
                ("createdBy", models.CharField(blank=True, max_length=255, null=True)),
                ("updatedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("deletedBy", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
