# Generated by Django 5.2.8 on 2025-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.BigIntegerField(default=1764667079254),
        ),
        migrations.AlterField(
            model_name="user",
            name="createdBy",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="deletedAt",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="deletedBy",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedBy",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
