# Generated by Django 5.2.8 on 2025-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_createdat_alter_user_createdby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.BigIntegerField(default=1764667305522),
        ),
    ]
