# Generated by Django 5.2.8 on 2025-12-02 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.BigIntegerField(default=1764670793425)),
                ("updatedAt", models.BigIntegerField(null=True)),
                ("deletedAt", models.BigIntegerField(null=True)),
                ("mediaUrl", models.CharField(blank=True, max_length=500, null=True)),
                ("mediaName", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.FloatField(default=0)),
                ("isExternal", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("createdBy", models.CharField(max_length=255, null=True)),
                ("updatedBy", models.CharField(max_length=255, null=True)),
                ("deletedBy", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "media",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("venue", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
                ("createdAt", models.BigIntegerField(default=1764670793426)),
                ("updatedAt", models.BigIntegerField(null=True)),
                ("deletedAt", models.BigIntegerField(null=True)),
                ("createdBy", models.CharField(max_length=255, null=True)),
                ("updatedBy", models.CharField(max_length=255, null=True)),
                ("deletedBy", models.CharField(max_length=255, null=True)),
                (
                    "imageId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.media",
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
    ]
