# Generated by Django 5.2.8 on 2025-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="createdAt",
            field=models.BigIntegerField(default=1764678675684),
        ),
        migrations.AlterField(
            model_name="media",
            name="createdAt",
            field=models.BigIntegerField(default=1764678675683),
        ),
    ]
